---
label: Project
hide_body: false
fields:
- name: id
  type: number
  label: Id
  description: ''
  default: 1
  required: true
  config:
    min: 1
    max: 
    step: 1
    required: true
- name: title
  type: text
  config:
    required: true
    min: 1
  label: Title
- name: images
  type: image_gallery
  config: {}
  label: Images
- name: description
  type: textarea
  default: ''
  config:
    required: true
    wysiwyg: false
    schema:
      format: markdown
    min: 0
  label: Description
